###

GET http://localhost:6688


### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "fullname": "Alice Chen",
    "workspace": "cos",
    "email": "alice@acme.org",
    "password": "123456"
}


### signin user
# @name signin
POST  http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "alice@acme.org",
    "password": "123456"
}
@token = {{signin.response.body.token}}

### get chat list


GET http://localhost:6688/api/chats
Authorization: Bearer {{token}}

### signin user with wrong password
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "tchen@acme.org",
    "password": "123456"
}

### get user list

GET http://localhost:6688/api/users
Authorization: Bearer {{token}}


### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "acme",
    "fullname": "Alice Chen",
    "email": "alice@acme.org",
    "password": "123456"
}

### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "acme",
    "fullname": "Alice Chen1",
    "email": "alice1@acme.org",
    "password": "123456"
}

### create chat
POST http://localhost:6688/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "acme",
    "members": [1, 2, 3],
    "public": false
}

### upload files

POST http://localhost:6688/api/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; filename="face.png"
Content-Type: application/octet-stream

< /Users/lawliet/Downloads/face.png
--MyBoundary
Content-Disposition: form-data; filename="hello.txt"
Content-Type: text/plain

Hello, World!
--MyBoundary--

### get files

GET http://localhost:6688/api/files/1/25d/bb4/5220d2af5bf19893ccfee91ecc9fa16263.png
Authorization: Bearer {{token}}

### send a message

POST http://localhost:6688/api/chats/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "Hello, World!",
    "files": []
}

### get messages

GET http://localhost:6688/api/chats/1/messages?limit=100
Authorization: Bearer {{token}}

### get chat
GET http://localhost:6688/api/chats/20
Authorization: Bearer {{token}}

### update chat
PATCH  http://localhost:6688/api/chats/25
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "lawliet"
}

### update chat
DELETE   http://localhost:6688/api/chats/25
Authorization: Bearer {{token}}
