server:
  port: 6688
  db_url: postgres://lawliet:postgres@localhost:5432/chat
auth:
  sk: |
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEIDMqmxCuzCa2m9aITCUaM97WFOb52B6DqkeIpd/XJkUw
    -----END PRIVATE KEY-----
  pk: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAw+EEpVfzmNBQk6Ke7lj6rSDppXWIITl1fh9vpOgQCOs=
    -----END PUBLIC KEY-----
